# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0

# Define a job to be invoked later in a workflow.

jobs:
  build:
    << *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          key: npm_packages
          paths:
            - /src/node_modules
      - run: npm run lint
  test:
    << *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm run test
  analyze:
    << *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - "npm_packages"
      - run: npm audit
      - run:
          command: echo "npm audit failed!!"
          when: on_fail

# Invoke jobs via workflows
workflows:
  react-slingshot-ci:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
